apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.coreBanking.name }}

spec:
  selector:
    app: {{ .Values.coreBanking.name }}

  ports:
    - protocol: TCP
      port: {{ .Values.coreBanking.port }}
      targetPort: {{ .Values.coreBanking.port }}

  type: ClusterIP
