apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.fundTransfer.name }}

spec:
  replicas: {{ .Values.fundTransfer.replicas }}

  strategy:
    type: RollingUpdate

    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: {{ .Values.fundTransfer.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.fundTransfer.name }}

    spec:
      containers:
        - name: {{ .Values.fundTransfer.name }}

          image: "{{ .Values.fundTransfer.image }}:{{ .Values.fundTransfer.tag }}"

          ports:
            - containerPort: {{ .Values.fundTransfer.port }}

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.fundTransfer.port }}

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.fundTransfer.port }}

            initialDelaySeconds: 20
            periodSeconds: 10
