# Deploy ONLY api-gateway
global:
  namespace: internet-banking

serviceRegistry:
  enabled: false

configServer:
  enabled: false

apiGateway:
  enabled: true
  name: internet-banking-api-gateway
  replicaCount: 1
  image:
    repository: saroja21/internet-banking-api-gateway
    tag: "main"
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 8080
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  healthCheck:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 15
    failureThreshold: 12

userService:
  enabled: false

coreBankingService:
  enabled: false

fundTransferService:
  enabled: false

utilityPaymentService:
  enabled: false

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
