# Deploy ONLY utility-payment-service
global:
  namespace: internet-banking

serviceRegistry:
  enabled: false

configServer:
  enabled: false

apiGateway:
  enabled: false

userService:
  enabled: false

coreBankingService:
  enabled: false

fundTransferService:
  enabled: false

utilityPaymentService:
  enabled: true
  name: internet-banking-utility-payment-service
  replicaCount: 1
  image:
    repository: saroja21/internet-banking-utility-payment-service
    tag: "main"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8084
  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "250m"
  healthCheck:
    enabled: true
    initialDelaySeconds: 240
    periodSeconds: 20
    failureThreshold: 20

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
