# ✓ Everything configurable goes here
replicaCount: 2
image:
  repository: tne736/core-banking-service
  tag: "2.0.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8092
  targetPort: 8092
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
