fundTransfer:
  name: fund-transfer-service

  replicas: 2

  image: fund-transfer-service

  tag: v2

  port: 8080

apiGateway:
  name: api-gateway-service

  replicas: 2

  image: api-gateway-service

  tag: v1

  port: 8081

coreBanking:
  name: core-banking-service

  replicas: 2

  image: core-banking-service

  tag: v1

  port: 8082

userService:
  name: user-service

  replicas: 2

  image: user-service

  tag: v1

  port: 8083
