global:
  namespace: internet-banking

# =========================
# SERVICE REGISTRY
# =========================
serviceRegistry:
  enabled: true
  name: service-registry

  replicaCount: 1

  image:
    repository: saroja21/service-registry
    tag: "main"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8761

  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"

    limits:
      memory: "1Gi"
      cpu: "250m"

  healthCheck:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 20
    failureThreshold: 20


# =========================
# CONFIG SERVER
# =========================
configServer:
  enabled: true
  name: config-server

  replicaCount: 1

  image:
    repository: saroja21/config-server
    tag: "main"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8888

  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"

    limits:
      memory: "1Gi"
      cpu: "250m"

  healthCheck:
    enabled: true
    initialDelaySeconds: 180
    periodSeconds: 20
    failureThreshold: 20


# =========================
# USER SERVICE
# =========================
userService:
  enabled: true
  name: user-service

  replicaCount: 1

  image:
    repository: saroja21/user-service
    tag: "main"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8083

  resources:
    requests:
      memory: "512Mi"
      cpu: "100m"

    limits:
      memory: "1Gi"
      cpu: "250m"

  healthCheck:
    enabled: true
    initialDelaySeconds: 240
    periodSeconds: 20
    failureThreshold: 20


# =========================
# DISABLED SERVICES
# =========================
apiGateway:
  enabled: false

coreBankingService:
  enabled: false

fundTransferService:
  enabled: false

utilityPaymentService:
  enabled: false


# =========================
# DEPLOYMENT STRATEGY
# =========================
strategy:
  type: RollingUpdate

  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
