fundTransfer:
  name: fund-transfer-service

  replicas: 2

  image: fund-transfer-service

  tag: v1

  port: 8080


apiGateway:
  name: api-gateway-service

  replicas: 2

  image: api-gateway-service

  tag: v1

  port: 8081
